### ISSUE TITLE
Installed as extension, got error.

### ISSUE THREAD

**Issue by garyo** [quasarframework/quasar-ui-qmarkdown#397]
**Describe the bug (with repro)**
I created a new Quasar project, did some work in it, then tried to do `quasar ext add @quasar/qmarkdown@next` and got this error:

```
% bun quasar ext add @quasar/qmarkdown@next
 App • Installing "@quasar/qmarkdown" Quasar App Extension

 App • Installing @quasar/quasar-app-extension-qmarkdown@next...
 App • [sync] Running "bun add --dev @quasar/quasar-app-extension-qmarkdown@next" in /Users/garyo/src/astrid/astrid-tutoring

bun add v1.0.1 (31aec4eb)

 installed @quasar/quasar-app-extension-qmarkdown@2.0.0-beta.10


 41 packages installed [2.53s]
node:internal/errors:491
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:400:5)
    at validateString (node:internal/validators:163:11)
    at join (node:path:1172:7)
    at #getScriptFile (file:///Users/garyo/src/astrid/astrid-tutoring/node_modules/@quasar/app-vite/lib/app-extension/AppExtensionInstance.js:327:22)
    at #getScript (file:///Users/garyo/src/astrid/astrid-tutoring/node_modules/@quasar/app-vite/lib/app-extension/AppExtensionInstance.js:339:39)
    at #getScriptPrompts (file:///Users/garyo/src/astrid/astrid-tutoring/node_modules/@quasar/app-vite/lib/app-extension/AppExtensionInstance.js:287:51)
    at AppExtensionInstance.install (file:///Users/garyo/src/astrid/astrid-tutoring/node_modules/@quasar/app-vite/lib/app-extension/AppExtensionInstance.js:201:49)
    at async file:///Users/garyo/src/astrid/astrid-tutoring/node_modules/@quasar/app-vite/lib/cmd/ext.js:90:3 {
  code: 'ERR_INVALID_ARG_TYPE'
}

Node.js v18.13.0
error: "quasar" exited with code 1 (SIGHUP)
```

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: latest (today)
 - Using bun 1.0.1
 - Node.js 18.13.0

**Comment by philippebourcier** [comment]
Same error on my side too (on Linux using plain "quasar ext add @quasar/qmarkdown@next")...
@hawkeye64 🙏🥺

**Comment by hawkeye64** [comment]
Are you guys still having an issue? This works for me:

```
$ quasar ext add @quasar/qmarkdown
 App • Installing "@quasar/qmarkdown" Quasar App Extension

 App • Installing @quasar/quasar-app-extension-qmarkdown...
 App • [sync] Running "pnpm add --save-dev @quasar/quasar-app-extension-qmarkdown" in /home/jeff/git/github/app-ext/other/test-markdown

Packages: +83
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 619, reused 557, downloaded 3, added 83, done

devDependencies:
+ @quasar/quasar-app-extension-qmarkdown 2.0.0

Done in 3.7s
? Do you want to be able to import markdown (*.md) files? Yes

 App • Updating /quasar.extensions.json for "@quasar/qmarkdown" extension ...
 App • Quasar App Extension "@quasar/qmarkdown" successfully installed.
 ```
and 
```
$ quasar ext add @quasar/qmarkdown@next
 App • Installing "@quasar/qmarkdown" Quasar App Extension

 App • Installing @quasar/quasar-app-extension-qmarkdown@next...
 App • [sync] Running "pnpm add --save-dev @quasar/quasar-app-extension-qmarkdown@next" in /home/jeff/git/github/app-ext/other/test-markdown

Packages: +1
+
Progress: resolved 619, reused 560, downloaded 0, added 1, done

devDependencies:
- @quasar/quasar-app-extension-qmarkdown 2.0.0
+ @quasar/quasar-app-extension-qmarkdown 2.0.0-beta.10 (2.0.0 is available)

Done in 2.1s
 App • Updating /quasar.extensions.json for "@quasar/qmarkdown" extension ...
 App • Quasar App Extension "@quasar/qmarkdown" successfully installed.
 ```
I am going to close this ticket as it doesn't really have anything to do with QMarkdown. If this is still an issue, open a ticket on the Quasar issues page as this would be a Quasar cli issue.
