### ISSUE TITLE
Vite build fails after installing the extension

### ISSUE THREAD

**Issue by jdmcalee** [quasarframework/quasar-ui-qmarkdown#406]
**Describe the bug**
After installing the extension, Vite fails to build with the following error:

    [vite] (client) error while updating dependencies:
    Error: Build failed with 1 error:
    node_modules/@quasar/quasar-app-extension-qmarkdown/src/boot/register.js:1:27: ERROR: Could not resolve "#q-app/wrappers"
        at failureErrorWithLog (/var/www/html/node_modules/esbuild/lib/main.js:1476:15)
        at /var/www/html/node_modules/esbuild/lib/main.js:945:25
        at /var/www/html/node_modules/esbuild/lib/main.js:1354:9
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**To Reproduce**
1. Open the Quasar Stackblitz: https://stackblitz.quasar.dev/
2. After it's up and running, in the terminal pane, Ctrl-C to get back to the prompt.
3. Run 'quasar ext add @quasar/qmarkdown'
4. Choose Y or n at the prompt about importing markdown (error occurs either way)
5. Run 'quasar dev'

**Expected behavior**
No errors, app renders properly

**Screenshots**
![image](https://github.com/user-attachments/assets/e33cf8e0-f257-4b23-87e5-ed91c0ae3b33)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version: 133.0.3

**Additional context**

**Comment by f3k-freek** [comment]
I've got the same problem. This is my setup:
I used `@quasar/cli@4.2.1` to init the project
I'm using typescript and vite.

When I run `quasar build` and then `quasar serve dist/spa` it works as expected. So it seems to be a problem with vite indeed.

**Comment by 0pen5un** [comment]
I've got the same problem. 
quasar - 2.17.5
 @quasar/app-vite - 2.0.4
@quasar/quasar-ui-qmarkdownv2.0.1
![图片](https://github.com/user-attachments/assets/94eab65e-b659-4b0a-aa81-adb4d05f952d)
When I run quasar build and then quasar serve dist/spa it works as expected.

**Comment by sonicviz** [comment]
Webpack broken as well. 
The issue I had was closed as fixed, but it was never tested because as soon as I did it was obviously not working. 
https://github.com/quasarframework/quasar-ui-qmarkdown/issues/401

**Comment by hawkeye64** [comment]
Has anyone tried v2.0.4?

**Comment by 2897924003** [comment]
> Has anyone tried v2.0.4?

I used version 2.0.4, and this issue exists. I can try using the latest version later.

**Comment by 0pen5un** [comment]
> Has anyone tried v2.0.4?  有人试过 v2.0.4 吗？

Using version 2.0.4 successfully

**Comment by jdmcalee** [comment]
I haven't been able to try it in my real app, but it does work in the stackblitz now.
