### ISSUE TITLE
Error on SSR mode first run

### ISSUE THREAD

**Issue by eladcandroid** [quasarframework/quasar-ui-qmarkdown#66]
1. Create a new Quasar project with:
```bash
npx @quasar/cli create checkssr2 
```
2. Add quasar ui markdown plugin
```bash
npx @quasar/cli ext add @quasar/qmarkdown
```
3. Run 
```bash
npx quasar dev -m ssr
```
4. Got this error:

```bash
/ -> error during render
/Users/mac/dev/quasar/checkssr2/node_modules/@quasar/quasar-ui-qmarkdown/src/index.js:1
import { version } from '../package.json'
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at compileFunction (<anonymous>)
    at wrapSafe (internal/modules/cjs/loader.js:1055:16)
    at Module._compile (internal/modules/cjs/loader.js:1103:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1159:10)
    at Module.load (internal/modules/cjs/loader.js:988:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1028:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at r (/Users/mac/dev/quasar/checkssr2/node_modules/vue-server-renderer/build.dev.js:9310:16)
    at Object.@quasar/quasar-ui-qmarkdown/src/index.js (webpack:/external "@quasar/quasar-ui-qmarkdown/src/index.js":1:0)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at Module../node_modules/@quasar/quasar-app-extension-qmarkdown/src/boot/register.js (node_modules/@quasar/quasar-app-extension-qmarkdown/src/boot/register.js:1:0)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at Module../.quasar/server-entry.js (server-bundle.js:332:118)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at Object.0 (server-bundle.js:1742:18)
```

Versions info:
Dev mode.......... ssr
Pkg quasar........ v1.6.1
Pkg @quasar/app... v1.4.3
@quasar/quasar-app-extension-qmarkdown: ^1.0.15

**Comment by hawkeye64** [comment]
@eladcandroid Thanks for reporting. Fixed in v1.0.16
